### PR TITLE
Updating the deps to use pre-terraform sdk provider

### PR DESCRIPTION
**Pull request by stack72**

### CODE REVIEW

**Comment by yspotts** [comment]
@stack72 thank you so much! I am reading through trying to learn...
I noticed you removed the tests from the makefile. Was that to avoid an issue? When I was trying this myself over the last couple of days (for my own fun), I was getting stuck in a dep on vault/consul, related to testing, so wondering if that was related. 

In any event, really appreciate it. I guess now, I "just" need to add all resources.

**Comment by stack72** [comment]
Hi @yspotts 

so the tests folder is outdated - we usually use "examples" now. I removed it as it was failing linting :)

Free free to ping me here or on community slack with any issues 

P.

**Comment by yspotts** [comment]
@stack72 I do have another question for now: I notice you created a `group` datasource as a springboard. Wondering - I dont see group listed as a datasource in the keycloak terraform provider. In `provider.go` for the keycloak terraform provider, I only see 6 datasources, and `group` is not one of them. Am I misunderstanding?

**Comment by stack72** [comment]
Hi @stack72 

Apologies as I was off for a few days. when you run `make` it will use the resources list from the provider map. As you can see the group datasource is here https://github.com/mrparkers/terraform-provider-keycloak/blob/master/provider/provider.go#L11

P.

**Comment by yspotts** [comment]
@stack72 no need to apologize!

duh! I handnt checked out the latest version of the provider! Now I see it. Sorry to trouble you

**Comment by stack72** [comment]
:)

**Comment by stack72** [comment]
Hey @yspotts 

As we are creating an official provider - I am going to go ahead and close this one out :)

Paul

**Pull request closed without merging**
